/* Live AI Quantum Sandbox */
(()=>{
const API='https://quantum-ai-1-og05.onrender.com';
const THREE_CDN='https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.min.js';
const GLTF_CDN='https://cdn.jsdelivr.net/npm/three@0.180.0/examples/js/exporters/GLTFExporter.js';
const GIF_CDN='https://cdn.jsdelivr.net/npm/gif.js@0.2.0/dist/gif.js';
let quantum=null, timer=null, recording=false;
const defaultCode='const scene = new THREE.Scene();\nscene.background = new THREE.Color(0x050816);\nconst camera = new THREE.PerspectiveCamera(55, innerWidth/innerHeight, 0.1, 100);\ncamera.position.z = 7;\nconst renderer = new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});\nrenderer.setSize(innerWidth,innerHeight);\ndocument.body.appendChild(renderer.domElement);\nscene.add(new THREE.AmbientLight(0x6688aa,1.5));\nconst light = new THREE.PointLight(0x8b5cf6,5,30); light.position.set(3,4,5); scene.add(light);\nconst p = window.QUANTUM_DATA.probabilities || {0:0.5,1:0.5};\nconst vals = Object.values(p); const a=Math.sqrt(vals[0]||0.5), b=Math.sqrt(vals[1]||0.5);\nconst sphere = new THREE.Mesh(new THREE.SphereGeometry(1,48,32),new THREE.MeshStandardMaterial({color:0x4db7ff,emissive:0x172c75,metalness:.35,roughness:.25}));\nscene.add(sphere);\nconst ring = new THREE.Mesh(new THREE.TorusGeometry(1.7,.035,12,96),new THREE.MeshBasicMaterial({color:0x9b6cff})); ring.rotation.x=Math.PI/2; scene.add(ring);\nfunction animate(t){requestAnimationFrame(animate); const time=t*.001; sphere.position.y=(b-a)*1.4; sphere.scale.setScalar(.75+.5*(a*a+b*b)); ring.rotation.z=time*(a-b); ring.rotation.y=time*(a+b)*.55; renderer.render(scene,camera)} animate(0);\naddEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});';
function clean(s){
  let x=String(s||'').trim();
  const blocks=[...x.matchAll(/\`\`\`(?:html|htm|css|javascript|js)?\\s*([\\s\\S]*?)\\s*\`\`\`/gi)];
  if(blocks.length) x=blocks.sort((a,b)=>b[1].length-a[1].length)[0][1].trim();
  if(!blocks.length){
    const htmlStart=x.search(/<!doctype\\s+html|<html[\\s>]/i);
    if(htmlStart>0) x=x.slice(htmlStart);
  }
  return x.trim();
}
function ui(){if(document.getElementById('qqSandboxBtn'))return;const b=document.createElement('button');b.id='qqSandboxBtn';b.className='newchat';b.textContent='⚛ Live Quantum Sandbox';b.onclick=open;document.querySelector('.sidebar')?.appendChild(b)}
function open(){if(document.getElementById('qqSandbox')){document.getElementById('qqSandbox').remove();return}const w=document.createElement('div');w.id='qqSandbox';w.innerHTML='<div class="qqs-bg"></div><section class="qqs-shell"><header><b>⚛ AI Quantum-Sandbox</b><span>Live code → real-time 3D</span><div class="qqs-buttons"><button id="qrun">Run</button><button id="qai">AI Generate</button><button id="qq">Quantum</button><button id="qglb">GLB</button><button id="qvid">Record WebM</button><button id="qgif">GIF</button><button id="qhtml">HTML</button><button id="qclose">×</button></div></header><main><div class="qleft"><div class="qprompt"><input id="qprompt" placeholder="Describe what you want, e.g. make a rotating 3D cube"></div><label>CODE <i id="qstatus">Ready</i></label><textarea id="qcode" spellcheck="false"></textarea></div><div class="qright"><label>LIVE OUTPUT <i id="qprob">Quantum: loading</i></label><iframe id="qframe" sandbox="allow-scripts allow-downloads"></iframe></div></main><footer>Paste HTML/CSS/JavaScript or ask AI for it. The right panel runs browser code live; Python and server-side code need a backend runtime.</footer></section>';
const st=document.createElement('style');st.textContent='#qqSandbox{position:fixed;inset:0;z-index:99999;font-family:system-ui}.qqs-bg{position:absolute;inset:0;background:#020617dd;backdrop-filter:blur(5px)}.qqs-shell{position:absolute;inset:3%;display:flex;flex-direction:column;background:#07101b;color:#eaf5ff;border:1px solid #29445e;border-radius:18px;overflow:hidden;box-shadow:0 20px 80px #000}.qqs-shell header{display:flex;align-items:center;gap:10px;padding:9px 12px;background:#0b1627;border-bottom:1px solid #29445e}.qqs-shell header b{font-size:15px}.qqs-shell header span{font-size:10px;color:#8ea9c1}.qqs-title{display:flex;flex-direction:column;min-width:150px}.qprompt{padding:8px;background:#050c16;border-bottom:1px solid #1d344a}.qprompt input{width:100%;box-sizing:border-box;border:1px solid #284763;border-radius:9px;background:#081522;color:#eaf5ff;outline:none;padding:9px 10px;font-size:11px}.qprompt input:focus{border-color:#4db7ff}.qqs-buttons{margin-left:auto;display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.qqs-buttons button{border:1px solid #315274;background:#0d1b2b;color:#dff4ff;border-radius:8px;padding:7px 8px;font-size:10px;font-weight:700}.qqs-shell main{display:grid;grid-template-columns:1fr 1fr;flex:1;min-height:0}.qleft,.qright{display:flex;flex-direction:column;min-width:0}.qleft{border-right:1px solid #29445e}.qqs-shell label{height:30px;padding:0 10px;display:flex;align-items:center;justify-content:space-between;background:#091321;color:#8fcaff;font-size:10px;font-weight:800}.qqs-shell label i{font-style:normal;color:#8aa2b8;font-weight:500}.qleft textarea{flex:1;resize:none;border:0;outline:0;background:#020711;color:#d9f1ff;padding:13px;font:12px/1.55 ui-monospace,monospace}.qright iframe{flex:1;border:0;background:#050816}.qqs-shell footer{padding:7px 10px;background:#091321;color:#70889e;font-size:10px;border-top:1px solid #29445e}@media(max-width:800px){.qqs-shell{inset:1%}.qqs-shell main{grid-template-columns:1fr}.qleft{height:45%;border-right:0;border-bottom:1px solid #29445e}.qright{height:55%}.qqs-shell header span{display:none}}';document.head.appendChild(st);document.body.appendChild(w);
document.getElementById('qcode').value=defaultCode;document.getElementById('qclose').onclick=()=>{w.remove();st.remove()};document.getElementById('qrun').onclick=run;document.getElementById('qai').onclick=ai;document.getElementById('qq').onclick=loadQuantum;document.getElementById('qglb').onclick=glb;document.getElementById('qvid').onclick=video;document.getElementById('qgif').onclick=gif;document.getElementById('qhtml').onclick=html;document.getElementById('qcode').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(run,250)});document.getElementById('qprompt').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();ai()}});loadQuantum().then(run)}
async function loadQuantum(){try{const r=await fetch(API+'/quantum',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qubits:2,shots:1000})});if(!r.ok)throw Error('HTTP '+r.status);const x=await r.json(),z=x.result||{},p={};(z.measurements||[]).forEach(v=>p[v.binary]=v.probability);if(!Object.keys(p).length&&z.counts)Object.entries(z.counts).forEach(([k,v])=>p[k]=v/(z.shots||1));quantum=Object.assign({},z,{probabilities:p});document.getElementById('qprob').textContent='Quantum: '+Object.entries(p).map(([k,v])=>k+' '+Number(v).toFixed(2)).join(' · ')}catch(e){quantum={qubits:2,shots:1000,probabilities:{'00':.25,'01':.25,'10':.25,'11':.25}};document.getElementById('qprob').textContent='Quantum: fallback demo'}}
function src(code){const q=JSON.stringify(quantum||{});return '<!doctype html><html><body style="margin:0;overflow:hidden;background:#050816"><script>window.QUANTUM_DATA='+q+';window.QUANTUM_PROBABILITIES=window.QUANTUM_DATA.probabilities||{};<\/script><script src="'+THREE_CDN+'"><\/script><script src="'+GLTF_CDN+'"><\/script><script src="'+GIF_CDN+'"><\/script><script>'+clean(code).replace(/<\/script/gi,'<\\/script')+'<\/script><script>window.addEventListener("message",async function(e){var m=e.data||{};try{if(m.type==="glb"){var root=window.scene||window.group||window.model;if(!root)throw Error("Expose window.scene for GLB export");var ex=new THREE.GLTFExporter();var out=await ex.parseAsync(root,{binary:true,onlyVisible:false,animations:window.animationClips||[]});var rd=new FileReader();rd.onload=function(){parent.postMessage({type:"download",name:"quantum-sandbox.glb",data:rd.result},"*")};rd.readAsDataURL(new Blob([out],{type:"model/gltf-binary"}))}if(m.type==="video"){var c=document.querySelector("canvas");if(!c)throw Error("No canvas");if(m.stop){if(window.rec&&window.rec.state!=="inactive")window.rec.stop();return}var ms=c.captureStream(60);var mt="video/webm;codecs=vp9";if(!MediaRecorder.isTypeSupported(mt))mt="video/webm";window.ch=[];window.rec=new MediaRecorder(ms,{mimeType:mt,videoBitsPerSecond:8000000});window.rec.ondataavailable=function(a){if(a.data.size)window.ch.push(a.data)};window.rec.onstop=function(){var rd=new FileReader();rd.onload=function(){parent.postMessage({type:"download",name:"quantum-sandbox.webm",data:rd.result},"*")};rd.readAsDataURL(new Blob(window.ch,{type:mt}))};window.rec.start()}if(m.type==="gif"){var c=document.querySelector("canvas");if(!c||!window.gifshot)throw Error("GIF unavailable");var imgs=[],start=performance.now();function cap(){imgs.push(c.toDataURL("image/png"));if(performance.now()-start<4000)setTimeout(cap,67);else gifshot.createGIF({images:imgs,interval:.067,gifWidth:Math.min(c.width,640),gifHeight:Math.min(c.height,360),numWorkers:2},function(o){if(o.error)throw Error(o.errorMsg||"GIF failed");parent.postMessage({type:"download",name:"quantum-sandbox.gif",data:o.image},"*")})}cap()}}catch(err){parent.postMessage({type:"error",message:err.message},"*")}});<\/script></body></html>'}

function looksLikeHTML(code){
  return /<!doctype\s+html|<html[\s>]|<head[\s>]|<body[\s>]|<script[\s>]|<style[\s>]|<canvas[\s>]|<div[\s>]/i.test(code);
}
function looksLikeCSS(code){
  return /^\s*(?:@media|@keyframes|[.#\w][^{]{0,80}\{[\s\S]*\}\s*)+$/i.test(code) && !/[;]\s*(?:const|let|var|function)\b/.test(code);
}
function bridge(){
  return '<script>window.addEventListener("message",function(e){var m=e.data||{};try{if(m.type==="video"){var c=document.querySelector("canvas");if(!c)throw Error("No canvas");if(m.stop){if(window.rec&&window.rec.state!=="inactive")window.rec.stop();return}var ms=c.captureStream(60),mt="video/webm;codecs=vp9";if(!MediaRecorder.isTypeSupported(mt))mt="video/webm";window.ch=[];window.rec=new MediaRecorder(ms,{mimeType:mt});window.rec.ondataavailable=function(a){if(a.data.size)window.ch.push(a.data)};window.rec.onstop=function(){var rd=new FileReader();rd.onload=function(){parent.postMessage({type:"download",name:"quantum-sandbox.webm",data:rd.result},"*")};rd.readAsDataURL(new Blob(window.ch,{type:mt}))};window.rec.start()}else if(m.type==="glb"){var root=window.scene||window.group||window.model;if(!root)throw Error("Expose window.scene for GLB export");if(!window.THREE||!THREE.GLTFExporter)throw Error("GLTFExporter unavailable");var ex=new THREE.GLTFExporter();ex.parse(root,function(out){var b=new Blob([out],{type:"model/gltf-binary"}),rd=new FileReader();rd.onload=function(){parent.postMessage({type:"download",name:"quantum-sandbox.glb",data:rd.result},"*")};rd.readAsDataURL(b)},{binary:true,onlyVisible:false});}}catch(err){parent.postMessage({type:"error",message:err.message},"*")}});<\\/script>';
}

function buildPreview(code){
  const q=JSON.stringify(quantum||{probabilities:{0:.5,1:.5}});
  const cleanCode=clean(code);
  if(looksLikeHTML(cleanCode)){
    let h=cleanCode.replace(/<\/script/gi,'<\\/script');
    if(/<head[\s>]/i.test(h)){
      h=h.replace(/<head[^>]*>/i,m=>m+'<script>window.QUANTUM_DATA='+q+';<\\/script><script src="'+THREE_CDN+'"><\\/script><script src="'+GLTF_CDN+'"><\\/script><script src="'+GIF_CDN+'"><\\/script>');
    }else if(/<html[\s>]/i.test(h)){
      h=h.replace(/<html[^>]*>/i,m=>m+'<head><script>window.QUANTUM_DATA='+q+';<\\/script><script src="'+THREE_CDN+'"><\\/script><script src="'+GLTF_CDN+'"><\\/script><script src="'+GIF_CDN+'"><\\/script></head>');
    }else{
      h='<!doctype html><html><head><script>window.QUANTUM_DATA='+q+';<\\/script><script src="'+THREE_CDN+'"><\\/script><script src="'+GLTF_CDN+'"><\\/script><script src="'+GIF_CDN+'"><\\/script></head><body>'+h+'</body></html>';
    }
    return h.replace(/<\/body>/i,bridge()+'</body>');
  }
  if(looksLikeCSS(cleanCode)){
    return '<!doctype html><html><head><style>'+cleanCode+'</style></head><body><div class="qq-css-preview">Live CSS preview</div></body></html>';
  }
  const js=cleanCode.replace(/<\/script/gi,'<\\/script');
  return '<!doctype html><html><head><style>html,body{margin:0;width:100%;height:100%;overflow:hidden}canvas{display:block}</style></head><body><script>window.QUANTUM_DATA='+q+';window.QUANTUM_PROBABILITIES=window.QUANTUM_DATA.probabilities||{};<\\/script><script src="'+THREE_CDN+'"><\\/script><script src="'+GLTF_CDN+'"><\\/script><script src="'+GIF_CDN+'"><\\/script><script>'+js+'<\\/script>'+bridge()+'</body></html>';
}
function run(){const f=document.getElementById('qframe');if(f)f.srcdoc=buildPreview(document.getElementById('qcode').value);const s=document.getElementById('qstatus');if(s)s.textContent='Running'}
async function ai(){const prompt=document.getElementById('qprompt').value.trim(),s=document.getElementById('qstatus');if(!prompt){s.textContent='Type a request first';document.getElementById('qprompt').focus();return}s.textContent='AI generating…';try{const instruction='User wants this to run in the browser sandbox: '+prompt+'\n\nReturn ONLY complete runnable HTML code. Put CSS inside <style> and JavaScript inside <script>. Do not use Markdown fences or explanations. For 3D use the provided global THREE object, not ES module imports. Make animations visibly run immediately. If creating a Three.js scene, expose it as window.scene for export. Never use Math.random for quantum-driven values; use window.QUANTUM_DATA.probabilities when the request is quantum-related.';const r=await fetch(API+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:instruction,history:[]})});const x=await r.json();if(!r.ok)throw Error(x.detail||'AI request failed');const answer=clean(x.answer||'');if(!answer)throw Error('AI returned empty code');document.getElementById('qcode').value=answer;run();s.textContent='AI output running'}catch(e){s.textContent='AI error: '+(e.message||'request failed')}}
function dl(d,n){const a=document.createElement('a');a.href=d;a.download=n;document.body.appendChild(a);a.click();a.remove()}
function glb(){document.getElementById('qframe')?.contentWindow.postMessage({type:'glb'},'*')}
function video(){const f=document.getElementById('qframe'),b=document.getElementById('qvid');if(!recording){recording=true;b.textContent='Stop WebM';f.contentWindow.postMessage({type:'video'},'*')}else{recording=false;b.textContent='Record WebM';f.contentWindow.postMessage({type:'video',stop:true},'*')}}
function gif(){document.getElementById('qstatus').textContent='Recording GIF…';document.getElementById('qframe')?.contentWindow.postMessage({type:'gif'},'*')}
function html(){const h=buildPreview(document.getElementById('qcode').value);dl('data:text/html;charset=utf-8,'+encodeURIComponent(h),'quantum-sandbox.html')}
window.addEventListener('message',e=>{const m=e.data||{};if(m.type==='download')dl(m.data,m.name);if(m.type==='error')document.getElementById('qstatus').textContent='Export error: '+m.message});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui);else ui();
})();